### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by ebezzam** [LCAV/LenslessPiCam#42]
Split files inside `lensless` into intuitive modules, e.g.:

- reconstruction
- evaluation
- mask design
- data

**Comment by YohannPerron** [comment]
First, the name `/lensless/data` could be confused with `/data ` . Depending on what we plan to put inside dataset could be a more fitting name.

Second, some file don't fall in any categories. As of now (with the proposed subfolder) a possible split would be:

- reconstruction
  - recon.py
  - admm.py
  - apdg.py
  - gradient_descent.py 
  - mirflickr.py
- evaluation
  - metrics.py
  - benchmark.py
  - plot.py ?
- mask design
  - empty for now
  - tools to generate psf from different mask design
- data or dataset
  - ParallelDataset from benchmark.py
  - A generated dataset (and helper function) [see](https://github.com/YohannPerron/LenslessPiCamYohann/blob/Unrolled-optimization/scripts/recon/unrolled_gradient_descent.py)
 
This leaves : 

- constant.py
- io.py
- rfft_convolve.py
- util.py

An option could be to add /io (as in torchvision) or/and /utils (as in pytorch) subfolders to the proposed categories. Unless we plan to increase the number of io files, /utils is probably enough.

**Comment by ebezzam** [comment]
thanks @YohannPerron 

some comments
- those modules make sense. I don't see a bit problem with have a `data` folder and a `data` module. We could also rename the `data` folder to `sample_data`
- `io` / `util` don't necessary need to be modules and could be standalone 
- `rfft_convolve` could go into `util`?
- in the works is a `Sensor` class which could also be its own module. constant.py could go into this

**Comment by ebezzam** [comment]
Handled with #62
